POST http://localhost:9000/api/v1/user/login
Content-Type: application/json

{
  "name": "1123a1",
  "password": "123"
}
###
POST http://localhost:9000/api/v1/user/register
Content-Type: application/json

{
"name": "1123a1",
"password": "123"
}

###
POST http://localhost:9000/api/v1/cart/add
Content-Type: application/json

{
  "sku_id": "13131",
  "quantity": 13131,
  "uid": "afdsakflsjfl"
}

###

POST http://localhost:9000/api/v1/cart/mget
Content-Type: application/json

{
  "page_size": "1",
  "page_num": 10,
  "uid": "930fbafc-f9ed-458f-a1cf-768d65f8825e"
}

###

GET http://localhost:9000/api/v1/user/get/f9c7ca1b-7995-4df4-bb2f-7b741feaae31
###
GET http://localhost:9000/api/v1/home/category/head
###
GET http://localhost:9000/api/v1/main/get_sku/261311

###

POST http://localhost:9000/api/v1/main/search
Content-Type: application/json

{
  "keyword": "菲",
  "page_size": 10,
  "page_num": 1
}

### 更新商品
POST http://localhost:9000/api/v1/cart/update
Content-Type: application/json

{
  "sku_id": "13131",
  "quantity": 2,
  "selected": true,
  "uid": "930fbafc-f9ed-458f-a1cf-768d65f8825e"
}

### 删除商品
POST http://localhost:9000/api/v1/cart/delete
Content-Type: application/json

{
  "skus": ["13131", "261311"],
  "uid": "930fbafc-f9ed-458f-a1cf-768d65f8825e"
}

### 秒杀接口
POST http://localhost:9000/api/v1/activity/seckill
Content-Type: application/json

{
  "user_id": "930fbafc-f9ed-458f-a1cf-768d65f8825e",
  "sku": "261311",
  "activity_id": "ACT2023"
}

### 抽奖接口
POST http://localhost:9000/api/v1/activity/lottery
Content-Type: application/json

{
  "user_id": "930fbafc-f9ed-458f-a1cf-768d65f8825e",
  "activity_id": "testtt"
}