name: Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 添加 Go 依赖缓存
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      # 设置 Go 模块
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # 使用你需要的 Go 版本

      

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: zym1614511838@gmail.com
          password: zhongyiming2003

      - name: 构建镜像
        run:
          docker build -t registry.cn-hangzhou.aliyuncs.com/lazyyy1/eshop_api .
          
      # 添加 Docker 层缓存
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 连接阿里云
        run: |
          docker login -u aliyun2526497059 -p zhongyiming2003 registry.cn-hangzhou.aliyuncs.com
          docker push registry.cn-hangzhou.aliyuncs.com/lazyyy1/eshop_api:latest;


  deployment:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 更新服务器
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 117.72.72.114
          username: root
          password: F1ly6kT?
          port: 22
          script:
            docker stop eshop_api;
            docker rm eshop_api;
            docker login -u aliyun2526497059 -p zhongyiming2003 registry.cn-hangzhou.aliyuncs.com;
            docker pull registry.cn-hangzhou.aliyuncs.com/lazyyy1/eshop_api;
            docker run -d --name eshop_api -p 9000:9000 --network 47bce5c74f589f4867dbd57e9ca9f808_env-network registry.cn-hangzhou.aliyuncs.com/lazyyy1/eshop_api:latest;